blank_issues_enabled: false
contact_links:
  - name: Roflcord Support Server
    url: https://discord.gg/D9uwnFnqmd
    about: If you need help regarding Roflcord, please join our support server!
  - name: Roflcord Installer
    url: https://github.com/Roflcord/Installer
    about: You can find the Roflcord Installer here
